import type { Kanji, Level, Question, Vocabulary } from '../types';

// Original course expansion. These topical selections are study guides, not an
// official JLPT list. Simple foundations are explicitly marked as review.
type Topic = 'daily' | 'people' | 'home' | 'shopping' | 'food' | 'travel' | 'transport' | 'work' | 'education' | 'health' | 'nature' | 'technology' | 'community' | 'culture' | 'feelings' | 'communication' | 'time' | 'services';
type LexicalEntry = Vocabulary & { topicId: Topic };
type LexicalQuestion = Question & { topicId: Topic; questionType: 'kanji-reading' | 'orthography' | 'vocabulary-context' | 'usage' | 'paraphrase' };
type Row = [slug: string, word: string, reading: string, meaning: string, wordClass: string, example: string, translation: string, review?: boolean];
const noun = 'noun';
const suru = 'noun / する verb';
const na = 'noun / な-adjective';
const gi = 'godan verb (intransitive)';
const gt = 'godan verb (transitive)';
const ii = 'ichidan verb (intransitive)';
const it = 'ichidan verb (transitive)';
const adjective = 'い-adjective';

const rows: Record<Topic, Row[]> = {
  daily: [
    ['wake','起きる','おきる','to wake up; to get up',ii,'毎朝６時に起きる。','I get up at six every morning.',true],
    ['sleep','寝る','ねる','to sleep; to go to bed',ii,'明日は早いので、もう寝る。','I have an early start tomorrow, so I am going to bed now.',true],
    ['wash','洗う','あらう','to wash',gt,'食べる前に手を洗う。','I wash my hands before eating.',true],
    ['polish','磨く','みがく','to brush; to polish',gt,'寝る前に歯を磨く。','I brush my teeth before bed.',true],
    ['change-clothes','着替える','きがえる','to change clothes','ichidan verb (transitive / intransitive uses)','帰ったら、部屋着に着替える。','When I get home, I change into clothes for relaxing at home.',true],
    ['tidy','片付ける','かたづける','to tidy up; to put away',it,'食事の後、テーブルを片付ける。','I clear the table after the meal.'],
    ['finish-errand','済ませる','すませる','to finish; to get something done',it,'昼休みに銀行で用事を済ませる。','I get my banking errand done during lunch.'],
    ['spend-time','過ごす','すごす','to spend time',gt,'休日は家でゆっくり過ごす。','I spend my days off relaxing at home.'],
    ['habit','習慣','しゅうかん','habit; custom',noun,'朝の散歩が習慣になりました。','My morning walk has become a habit.'],
    ['everyday','日常','にちじょう','everyday life',noun,'日常の出来事を日記に書いています。','I write everyday events in my diary.'],
    ['going-out','外出','がいしゅつ','going out',suru,'外出する前に窓を閉めます。','I close the windows before going out.'],
    ['walk','散歩','さんぽ','walk; stroll',suru,'夕食の後、近所を散歩します。','I take a walk around the neighborhood after dinner.',true],
    ['break','休憩','きゅうけい','break; rest',suru,'１時間働いたら、短い休憩を取ります。','After working for an hour, I take a short break.'],
    ['errand','用事','ようじ','errand; something to attend to',noun,'午後は用事があるので、先に帰ります。','I have something to attend to this afternoon, so I will leave first.'],
    ['rising','起床','きしょう','getting up; rising from bed',suru,'起床の時間を毎日記録しています。','I record the time I get up every day.'],
    ['bedtime','就寝','しゅうしん','going to bed',suru,'就寝の１時間前には仕事を終えます。','I finish work an hour before going to bed.'],
    ['alarm','目覚まし','めざまし','alarm clock; alarm',noun,'目覚ましを７時にセットしました。','I set my alarm for seven.'],
    ['handwashing','手洗い','てあらい','handwashing',noun,'外から帰ったら、手洗いを忘れないでください。','Do not forget to wash your hands when you return from outside.'],
    ['toothbrushing','歯磨き','はみがき','toothbrushing',noun,'朝の歯磨きに３分かけています。','I spend three minutes brushing my teeth in the morning.',true],
    ['getting-ready','身支度','みじたく','getting dressed and ready',suru,'出かける前の身支度に時間がかかります。','Getting dressed and ready before going out takes time.'],
    ['effort','手間','てま','time and effort; trouble',noun,'この料理はあまり手間がかかりません。','This dish does not take much time or effort.'],
    ['turn','順番','じゅんばん','order; turn in a sequence',noun,'順番に一人ずつ入ってください。','Please enter one at a time in order.'],
    ['nap','昼寝','ひるね','afternoon nap',suru,'休日は３０分ほど昼寝をします。','On days off, I take a nap for about thirty minutes.'],
  ],
  people: [
    ['family','家族','かぞく','family',noun,'家族と一緒に夕食を食べます。','I eat dinner with my family.',true],
    ['relative','親戚','しんせき','relative; relatives',noun,'週末に親戚が遊びに来ます。','Some relatives are coming to visit this weekend.'],
    ['couple','夫婦','ふうふ','married couple; husband and wife',noun,'隣の夫婦はいつも一緒に散歩しています。','The married couple next door always take walks together.'],
    ['husband','夫','おっと','one’s husband',noun,'夫は今日は家で仕事をしています。','My husband is working at home today.',true],
    ['wife','妻','つま','one’s wife',noun,'妻と旅行の計画を立てました。','I made travel plans with my wife.',true],
    ['son','息子','むすこ','son',noun,'息子は来年、小学校に入ります。','My son will start elementary school next year.',true],
    ['daughter','娘','むすめ','daughter',noun,'娘は絵を描くのが好きです。','My daughter likes drawing.',true],
    ['grandfather','祖父','そふ','one’s grandfather',noun,'祖父は毎朝新聞を読みます。','My grandfather reads the newspaper every morning.',true],
    ['grandmother','祖母','そぼ','one’s grandmother',noun,'祖母に電話をかけました。','I called my grandmother.',true],
    ['grandchild','孫','まご','grandchild',noun,'祖母は孫に絵本を読みました。','The grandmother read a picture book to her grandchild.'],
    ['siblings','兄弟','きょうだい','siblings; brothers',noun,'私には兄弟が二人います。','I have two siblings.',true],
    ['sisters','姉妹','しまい','sisters',noun,'あの姉妹は同じ学校に通っています。','Those sisters attend the same school.'],
    ['friend','友人','ゆうじん','friend',noun,'大学時代の友人に会いました。','I met a friend from my university days.'],
    ['colleague','同僚','どうりょう','colleague',noun,'同僚と昼ご飯を食べに行きました。','I went out for lunch with a colleague.'],
    ['superior','上司','じょうし','superior at work; manager',noun,'上司に休暇の相談をしました。','I discussed taking time off with my manager.'],
    ['senior','先輩','せんぱい','senior colleague or student',noun,'先輩が仕事のやり方を教えてくれました。','A senior colleague taught me how to do the work.'],
    ['junior','後輩','こうはい','junior colleague or student',noun,'後輩に教室の場所を説明しました。','I explained the classroom’s location to a junior student.'],
    ['neighbor','隣人','りんじん','neighbor',noun,'引っ越した日に隣人に挨拶しました。','I greeted my neighbor on the day I moved in.'],
    ['acquaintance','知り合い','しりあい','acquaintance; someone one knows',noun,'駅で知り合いを見かけました。','I spotted an acquaintance at the station.'],
    ['companion','仲間','なかま','companion; fellow member',noun,'同じ趣味を持つ仲間が増えました。','I have gained more friends who share my hobby.'],
    ['other-person','相手','あいて','other person; partner; opponent',noun,'相手の話を最後まで聞きましょう。','Let us listen to the other person until they finish.'],
    ['care','世話','せわ','care; looking after someone',suru,'旅行中は妹が猫の世話をしてくれます。','My younger sister will look after my cat while I travel.'],
    ['personality','性格','せいかく','personality; character',noun,'弟は明るい性格です。','My younger brother has a cheerful personality.'],
  ],
  home: [
    ['room','部屋','へや','room',noun,'部屋の窓を開けました。','I opened the window in my room.',true],
    ['entrance','玄関','げんかん','entrance area',noun,'靴は玄関で脱いでください。','Please take off your shoes in the entrance area.',true],
    ['hallway','廊下','ろうか','hallway; corridor',noun,'廊下に荷物を置かないでください。','Please do not leave luggage in the hallway.'],
    ['kitchen','台所','だいどころ','kitchen',noun,'台所で夕食を作っています。','I am making dinner in the kitchen.',true],
    ['living-room','居間','いま','living room',noun,'家族は居間でテレビを見ています。','The family is watching television in the living room.'],
    ['bedroom','寝室','しんしつ','bedroom',noun,'寝室には小さな机があります。','There is a small desk in the bedroom.'],
    ['floor','床','ゆか','floor',noun,'床に落ちた水を拭きました。','I wiped up water that had spilled on the floor.'],
    ['wall','壁','かべ','wall',noun,'壁に時計を掛けました。','I hung a clock on the wall.'],
    ['ceiling','天井','てんじょう','ceiling',noun,'この部屋は天井が高いです。','This room has a high ceiling.'],
    ['window','窓','まど','window',noun,'窓から公園が見えます。','I can see the park from the window.',true],
    ['roof','屋根','やね','roof',noun,'雨で屋根がぬれています。','The roof is wet from the rain.'],
    ['stairs','階段','かいだん','stairs',noun,'３階まで階段を使います。','I take the stairs up to the third floor.',true],
    ['furniture','家具','かぐ','furniture',noun,'新しい部屋に合う家具を探しています。','I am looking for furniture that suits my new room.'],
    ['shelf','棚','たな','shelf',noun,'本を棚に並べました。','I arranged the books on the shelf.'],
    ['drawer','引き出し','ひきだし','drawer',noun,'かぎは机の引き出しにあります。','The key is in the desk drawer.'],
    ['mirror','鏡','かがみ','mirror',noun,'出かける前に鏡を見ました。','I looked in the mirror before going out.',true],
    ['blanket','毛布','もうふ','blanket',noun,'寒いので、毛布をもう一枚使います。','It is cold, so I will use another blanket.'],
    ['bedding','布団','ふとん','futon; Japanese bedding',noun,'朝、布団を押し入れにしまいます。','I put the futon away in the closet in the morning.'],
    ['heating','暖房','だんぼう','heating',noun,'寒くなったので、暖房をつけました。','It got cold, so I turned on the heating.'],
    ['cooling','冷房','れいぼう','air conditioning for cooling',noun,'冷房の温度を少し上げました。','I raised the air-conditioning temperature a little.'],
    ['rent','家賃','やちん','rent for a residence',noun,'家賃は毎月末に払います。','I pay the rent at the end of each month.'],
    ['moving','引っ越し','ひっこし','moving house',suru,'引っ越しの前に荷物を減らします。','I reduce my belongings before moving house.'],
    ['cleaning','掃除','そうじ','cleaning',suru,'土曜日に部屋の掃除をします。','I clean my room on Saturdays.',true],
  ],
  shopping: [
    ['price','値段','ねだん','price',noun,'買う前に値段を確認しました。','I checked the price before buying it.',true],
    ['pricing','価格','かかく','price; monetary value',noun,'商品の価格が少し上がりました。','The product’s price has risen a little.'],
    ['product','商品','しょうひん','product; merchandise',noun,'この商品には１年の保証があります。','This product comes with a one-year warranty.'],
    ['item','品物','しなもの','goods; item',noun,'注文した品物が届きました。','The item I ordered arrived.'],
    ['sales-area','売り場','うりば','sales floor; department',noun,'靴の売り場は２階です。','The shoe department is on the second floor.'],
    ['payment','支払い','しはらい','payment',noun,'支払いは現金でお願いします。','Please pay in cash.'],
    ['cash','現金','げんきん','cash',noun,'この店では現金しか使えません。','This shop accepts only cash.'],
    ['change-money','お釣り','おつり','change returned after payment',noun,'１０００円払って、お釣りを受け取りました。','I paid one thousand yen and received my change.'],
    ['discount','割引','わりびき','discount',suru,'学生は１０％の割引を受けられます。','Students can receive a ten-percent discount.'],
    ['half-price','半額','はんがく','half price',noun,'閉店前に弁当が半額になりました。','The boxed lunches became half price before closing.'],
    ['return-goods','返品','へんぴん','returning purchased goods',suru,'サイズが合わないので、返品をお願いしました。','The size did not fit, so I requested a return.'],
    ['exchange','交換','こうかん','exchange; replacement',suru,'壊れた部品の交換が必要です。','The broken part needs to be replaced.'],
    ['sold-out','売り切れ','うりきれ','sold out; out of stock',noun,'人気のお菓子はもう売り切れでした。','The popular sweets were already sold out.'],
    ['inventory','在庫','ざいこ','stock; inventory',noun,'別の店に在庫があるか調べます。','I will check whether another branch has it in stock.'],
    ['order','注文','ちゅうもん','order for goods or food',suru,'インターネットで本を注文しました。','I ordered a book online.',true],
    ['bag','袋','ふくろ','bag; sack',noun,'買った野菜を袋に入れました。','I put the vegetables I bought in a bag.',true],
    ['box','箱','はこ','box',noun,'箱の中に食器が入っています。','There are dishes in the box.',true],
    ['wrapping','包装','ほうそう','wrapping; packaging',suru,'贈り物なので、包装をお願いしました。','It is a gift, so I asked for it to be wrapped.'],
    ['budget','予算','よさん','budget',noun,'旅行の予算は５万円です。','My travel budget is fifty thousand yen.'],
    ['quality','品質','ひんしつ','quality of goods',noun,'値段だけでなく、品質も大切です。','Quality matters as well as price.'],
    ['quantity','量','りょう','quantity; amount',noun,'一人で食べるには量が多すぎます。','There is too much for one person to eat.'],
    ['try-clothes','試着','しちゃく','trying on clothes',suru,'買う前に試着してもいいですか。','May I try it on before buying it?'],
    ['special-sale','特売','とくばい','special sale',suru,'今日は卵の特売があります。','There is a special sale on eggs today.'],
  ],
  food: [
    ['meal','食事','しょくじ','meal; eating a meal',suru,'家族と食事をする時間が好きです。','I enjoy the time I spend eating with my family.',true],
    ['breakfast','朝食','ちょうしょく','breakfast',noun,'朝食にはパンと卵を食べます。','I eat bread and eggs for breakfast.',true],
    ['lunch','昼食','ちゅうしょく','lunch',noun,'昼食は会社の食堂で食べました。','I had lunch in the company cafeteria.',true],
    ['dinner','夕食','ゆうしょく','evening meal; dinner',noun,'夕食の前に手を洗いましょう。','Let us wash our hands before dinner.',true],
    ['ingredient','材料','ざいりょう','material; ingredient',noun,'料理の材料を買いに行きます。','I am going to buy ingredients for cooking.'],
    ['seasoning','調味料','ちょうみりょう','seasoning; condiment',noun,'調味料は少しずつ加えてください。','Please add the seasonings a little at a time.'],
    ['taste','味','あじ','taste; flavor',noun,'このスープは優しい味がします。','This soup has a gentle flavor.',true],
    ['salt','塩','しお','salt',noun,'塩を少し入れてください。','Please add a little salt.',true],
    ['sugar','砂糖','さとう','sugar',noun,'コーヒーに砂糖を入れません。','I do not put sugar in my coffee.',true],
    ['soy-sauce','しょうゆ','しょうゆ','soy sauce',noun,'魚にしょうゆを少しかけます。','I put a little soy sauce on the fish.',true],
    ['oil','油','あぶら','oil',noun,'フライパンに油を入れます。','I put oil in the frying pan.'],
    ['vegetable','野菜','やさい','vegetable; vegetables',noun,'毎日いろいろな野菜を食べます。','I eat various vegetables every day.',true],
    ['fruit','果物','くだもの','fruit',noun,'食後に果物を食べました。','I ate fruit after the meal.',true],
    ['egg','卵','たまご','egg',noun,'卵を二つ使って料理を作ります。','I will use two eggs to make the dish.',true],
    ['meat','肉','にく','meat',noun,'肉は冷蔵庫に入れてください。','Please put the meat in the refrigerator.',true],
    ['fish','魚','さかな','fish',noun,'市場で新鮮な魚を買いました。','I bought fresh fish at the market.',true],
    ['grill','焼く','やく','to grill; to bake; to toast',gt,'朝はパンを焼く。','I toast bread in the morning.',true],
    ['simmer','煮る','にる','to boil or simmer food',it,'野菜を柔らかくなるまで煮る。','I simmer the vegetables until they are tender.'],
    ['steam','蒸す','むす','to steam food',gt,'野菜を蒸すと、甘みが出る。','Steaming vegetables brings out their sweetness.'],
    ['deep-fry','揚げる','あげる','to deep-fry',it,'魚を油で揚げる。','I deep-fry the fish in oil.'],
    ['mix','混ぜる','まぜる','to mix; to stir together',it,'卵と牛乳をよく混ぜる。','I mix the eggs and milk well.'],
    ['cool-food','冷ます','さます','to cool something down',gt,'熱いスープを少し冷ます。','I cool the hot soup down a little.'],
  ],
  travel: [
    ['trip','旅行','りょこう','travel; trip',suru,'夏休みに家族で旅行をします。','My family will take a trip during summer vacation.',true],
    ['sightseeing','観光','かんこう','sightseeing; tourism',suru,'午前中は町の観光をしました。','I went sightseeing around town in the morning.'],
    ['destination','目的地','もくてきち','destination',noun,'目的地に着くまで、あと１時間です。','We have one more hour until we reach our destination.'],
    ['lodging','宿泊','しゅくはく','lodging; staying overnight',suru,'宿泊の費用には朝食が含まれています。','The lodging cost includes breakfast.'],
    ['inn','旅館','りょかん','Japanese-style inn',noun,'温泉のある旅館に泊まりました。','I stayed at an inn with a hot spring.'],
    ['reservation','予約','よやく','reservation; booking',suru,'ホテルの予約を確認しました。','I checked my hotel reservation.',true],
    ['stay','滞在','たいざい','stay in a place',suru,'京都に３日間滞在しました。','I stayed in Kyoto for three days.'],
    ['departure','出発','しゅっぱつ','departure',suru,'出発の前に荷物を確認します。','I check my luggage before departure.'],
    ['arrival','到着','とうちゃく','arrival',suru,'飛行機の到着が３０分遅れています。','The plane’s arrival is delayed by thirty minutes.'],
    ['information-office','案内所','あんないじょ','information office; information desk',noun,'駅の案内所で地図をもらいました。','I got a map at the station information office.'],
    ['souvenir','土産','みやげ','souvenir; gift brought back from a trip',noun,'家族に土産を買いました。','I bought souvenirs for my family.'],
    ['scenery','景色','けしき','scenery; view',noun,'窓から山の景色を楽しみました。','I enjoyed the mountain scenery from the window.'],
    ['map','地図','ちず','map',noun,'地図でホテルの場所を調べます。','I will look up the hotel’s location on a map.',true],
    ['get-lost','迷う','まよう','to get lost; to be undecided',gi,'知らない町では道に迷うことがある。','I sometimes get lost in unfamiliar towns.'],
    ['stay-overnight','泊まる','とまる','to stay overnight',gi,'今夜は駅の近くのホテルに泊まる。','I will stay at a hotel near the station tonight.',true],
    ['luggage','荷物','にもつ','luggage; belongings; parcel',noun,'重い荷物を受付に預けました。','I left my heavy luggage at reception.',true],
    ['tourist','観光客','かんこうきゃく','tourist',noun,'この町には外国からの観光客が多いです。','This town has many tourists from abroad.'],
    ['famous-place','名所','めいしょ','famous place; place of interest',noun,'町の名所を歩いて回りました。','I visited the town’s sights on foot.'],
    ['overseas','海外','かいがい','overseas; abroad',noun,'海外で働くことに興味があります。','I am interested in working abroad.'],
    ['domestic','国内','こくない','within a country; domestic',noun,'今回は国内を旅行します。','This time I will travel within the country.'],
    ['day-trip','日帰り','ひがえり','day trip; returning the same day',noun,'日帰りで温泉に行きました。','I went to a hot spring on a day trip.'],
    ['travel-expense','旅費','りょひ','travel expenses',noun,'旅費を節約するため、バスを使いました。','I took a bus to save on travel expenses.'],
  ],
  transport: [
    ['traffic','交通','こうつう','traffic; transportation',noun,'この町は交通が便利です。','Transportation is convenient in this town.'],
    ['fare','運賃','うんちん','transportation fare',noun,'駅までの運賃は２１０円です。','The fare to the station is 210 yen.'],
    ['transfer','乗り換え','のりかえ','transfer between vehicles',noun,'この路線なら乗り換えは１回です。','This route requires one transfer.'],
    ['one-way','片道','かたみち','one way',noun,'会社まで片道４０分かかります。','It takes forty minutes each way to get to work.'],
    ['round-trip','往復','おうふく','round trip; going and returning',suru,'駅まで往復すると、３０分かかります。','A round trip to the station takes thirty minutes.'],
    ['last-train','終電','しゅうでん','last train of the day',noun,'終電に間に合うように店を出ました。','I left the shop in time to catch the last train.'],
    ['first-train','始発','しはつ','first service; service starting at a station',noun,'明日は始発の電車に乗ります。','Tomorrow I will take the first train of the day.'],
    ['timetable','時刻表','じこくひょう','timetable',noun,'バスの時刻表を確認しました。','I checked the bus timetable.'],
    ['ticket-gate','改札','かいさつ','ticket gate; ticket inspection',noun,'改札の前で友人を待ちました。','I waited for a friend in front of the ticket gates.'],
    ['ticket','切符','きっぷ','ticket',noun,'電車の切符を２枚買いました。','I bought two train tickets.',true],
    ['commuter-pass','定期券','ていきけん','commuter pass',noun,'定期券を使って会社に通っています。','I commute to work using a commuter pass.'],
    ['bus-stop','停留所','ていりゅうじょ','stop for buses or trams',noun,'次の停留所で降りてください。','Please get off at the next stop.'],
    ['traffic-jam','渋滞','じゅうたい','traffic jam; congestion',suru,'道路の渋滞でバスが遅れています。','The bus is delayed because of traffic congestion.'],
    ['parking','駐車','ちゅうしゃ','parking a vehicle',suru,'ここでは駐車が禁止されています。','Parking is prohibited here.'],
    ['boarding','乗車','じょうしゃ','boarding; riding in a vehicle',suru,'乗車の前に切符を買ってください。','Please buy a ticket before boarding.'],
    ['alighting','降車','こうしゃ','getting off a vehicle',suru,'降車の際は、足元にご注意ください。','Please watch your step when getting off.'],
    ['crosswalk','横断歩道','おうだんほどう','pedestrian crossing',noun,'横断歩道を渡って、右に曲がります。','Cross the pedestrian crossing and turn right.'],
    ['signal','信号','しんごう','traffic light; signal',noun,'信号が青になるまで待ちましょう。','Let us wait until the light turns green.'],
    ['intersection','交差点','こうさてん','intersection; crossroads',noun,'次の交差点を左に曲がってください。','Please turn left at the next intersection.'],
    ['rail-track','線路','せんろ','railway track',noun,'線路の近くには入らないでください。','Please do not go near the railway tracks.'],
    ['lateness','遅刻','ちこく','arriving late',suru,'寝坊して授業に遅刻しました。','I overslept and arrived late for class.'],
    ['commute','通勤','つうきん','commuting to work',suru,'毎日、自転車で通勤しています。','I commute to work by bicycle every day.'],
  ],
  work: [
    ['meeting','会議','かいぎ','meeting; conference',noun,'会議で新しい計画について話しました。','We discussed the new plan at the meeting.'],
    ['workplace','職場','しょくば','workplace',noun,'職場まで歩いて通っています。','I walk to my workplace.'],
    ['salary','給料','きゅうりょう','salary; pay',noun,'給料の一部を毎月貯金しています。','I save part of my salary every month.'],
    ['overtime','残業','ざんぎょう','overtime work',suru,'今日は残業をせずに帰ります。','I will leave without working overtime today.'],
    ['leave','休暇','きゅうか','leave; vacation from work',noun,'来月、１週間の休暇を取ります。','I will take a week of leave next month.'],
    ['documents','書類','しょるい','documents; papers',noun,'必要な書類をかばんに入れました。','I put the necessary documents in my bag.'],
    ['report','報告','ほうこく','report; reporting',suru,'作業の結果を上司に報告しました。','I reported the work results to my manager.'],
    ['in-charge','担当','たんとう','being in charge; person responsible',suru,'この商品の担当は山田さんです。','Yamada is in charge of this product.'],
    ['interview','面接','めんせつ','interview',suru,'来週、会社の面接を受けます。','I have a job interview next week.'],
    ['employment','就職','しゅうしょく','finding or starting employment',suru,'卒業後、地元の会社に就職しました。','After graduating, I started working at a local company.'],
    ['change-job','転職','てんしょく','changing jobs',suru,'転職について友人に相談しました。','I talked to a friend about changing jobs.'],
    ['leave-job','退職','たいしょく','leaving a job; retirement',suru,'父は去年、長く勤めた会社を退職しました。','My father left the company he had worked at for many years last year.'],
    ['duty','勤務','きんむ','working; duty',suru,'勤務の時間は午前９時からです。','My working hours start at nine in the morning.'],
    ['task','作業','さぎょう','task; practical work',suru,'この作業には２時間かかります。','This task takes two hours.'],
    ['business-duty','業務','ぎょうむ','business duties; operations',noun,'午前中に業務を終えました。','I finished my work duties in the morning.'],
    ['responsibility','責任','せきにん','responsibility',noun,'自分の仕事には責任を持ちます。','I take responsibility for my own work.'],
    ['experience','経験','けいけん','experience',suru,'接客の経験が３年あります。','I have three years of customer-service experience.'],
    ['proposal','提案','ていあん','proposal; suggestion',suru,'会議で新しい方法を提案しました。','I proposed a new method at the meeting.'],
    ['transaction','取引','とりひき','business transaction; dealings',suru,'この会社とは長く取引をしています。','We have done business with this company for a long time.'],
    ['contract','契約','けいやく','contract; agreement',suru,'契約の内容をよく読んでください。','Please read the contract carefully.'],
    ['training','研修','けんしゅう','workplace training',suru,'新人は１週間の研修を受けます。','New employees undergo a week of training.'],
    ['evaluation','評価','ひょうか','evaluation; assessment',suru,'仕事の評価について上司と話しました。','I discussed my work evaluation with my manager.'],
  ],
  education: [
    ['class','授業','じゅぎょう','class; lesson',noun,'授業は午前９時に始まります。','Class starts at nine in the morning.',true],
    ['lecture','講義','こうぎ','lecture',suru,'大学で歴史の講義を受けています。','I am attending history lectures at university.'],
    ['exam','試験','しけん','test; examination',suru,'試験の前にノートを読み直しました。','I reread my notes before the exam.',true],
    ['grades','成績','せいせき','grades; academic performance',noun,'毎日勉強して、成績が上がりました。','I studied every day, and my grades improved.'],
    ['pass-exam','合格','ごうかく','passing an examination',suru,'運転免許の試験に合格しました。','I passed the driving-license test.'],
    ['fail-exam','不合格','ふごうかく','failing an examination',noun,'今回は不合格でしたが、もう一度受けます。','I did not pass this time, but I will take it again.'],
    ['revision','復習','ふくしゅう','reviewing what one has learned',suru,'授業の後に復習をします。','I review what I learned after class.'],
    ['preparation-study','予習','よしゅう','studying material before class',suru,'明日の授業の予習をしています。','I am preparing the material for tomorrow’s class.'],
    ['learning','学習','がくしゅう','learning; study',suru,'自分に合う学習の方法を探しています。','I am looking for a study method that suits me.'],
    ['practice','練習','れんしゅう','practice; training',suru,'毎日、日本語を話す練習をします。','I practice speaking Japanese every day.',true],
    ['research','研究','けんきゅう','research',suru,'大学で海の生物の研究をしています。','I research marine organisms at university.'],
    ['assignment','課題','かだい','assignment; task; issue to address',noun,'週末までに課題を終わらせます。','I will finish the assignment by the weekend.'],
    ['submission','提出','ていしゅつ','submission; handing in',suru,'レポートの提出は金曜日までです。','Reports must be submitted by Friday.'],
    ['course','講座','こうざ','course; series of classes',noun,'料理の講座に申し込みました。','I signed up for a cooking course.'],
    ['specialization','専門','せんもん','specialization; field of expertise',noun,'私の専門は経済です。','My field of study is economics.'],
    ['further-education','進学','しんがく','advancing to a higher level of education',suru,'高校を出た後、大学に進学しました。','After high school, I went on to university.'],
    ['graduation','卒業','そつぎょう','graduation',suru,'妹は今年、高校を卒業します。','My younger sister will graduate from high school this year.'],
    ['school-entry','入学','にゅうがく','entering a school',suru,'入学の前に教科書を買いました。','I bought textbooks before starting school.'],
    ['textbook','教科書','きょうかしょ','textbook',noun,'教科書の２０ページを開いてください。','Please open your textbook to page twenty.'],
    ['dictionary','辞書','じしょ','dictionary',noun,'知らない言葉を辞書で調べます。','I look up unfamiliar words in a dictionary.',true],
    ['understanding','理解','りかい','understanding; comprehension',suru,'先生の説明で内容を理解できました。','The teacher’s explanation helped me understand the content.'],
    ['memorize','覚える','おぼえる','to learn; to memorize; to remember',it,'毎日、新しい漢字を三つ覚える。','I learn three new kanji every day.',true],
  ],
  health: [
    ['symptom','症状','しょうじょう','symptom; symptoms',noun,'どんな症状があるか医者に話しました。','I told the doctor what symptoms I had.'],
    ['pain','痛み','いたみ','pain',noun,'昨日から膝に痛みがあります。','I have had pain in my knee since yesterday.'],
    ['fever','熱','ねつ','fever; heat',noun,'熱があるので、今日は家で休みます。','I have a fever, so I will rest at home today.',true],
    ['cough','咳','せき','cough',noun,'咳が続いているので、病院に行きました。','My cough has persisted, so I went to the hospital.'],
    ['headache','頭痛','ずつう','headache',noun,'頭痛がひどくて、仕事を休みました。','I had a bad headache and took the day off work.'],
    ['stomachache','腹痛','ふくつう','abdominal pain; stomachache',noun,'腹痛のため、早く帰りました。','I went home early because of abdominal pain.'],
    ['cold','風邪','かぜ','common cold',noun,'風邪をひいて、声が出ません。','I have a cold and have lost my voice.',true],
    ['medical-exam','診察','しんさつ','medical examination; consultation',suru,'医師の診察を受けました。','I had a medical consultation with a doctor.'],
    ['treatment','治療','ちりょう','medical treatment',suru,'歯の治療が終わりました。','My dental treatment is finished.'],
    ['medicine','薬','くすり','medicine',noun,'薬の飲み方を薬剤師に聞きました。','I asked the pharmacist how to take the medicine.',true],
    ['prescription','処方箋','しょほうせん','prescription',noun,'薬局に処方箋を出しました。','I handed the prescription to the pharmacy.'],
    ['body-temperature','体温','たいおん','body temperature',noun,'体温を測ってから学校に行きます。','I check my temperature before going to school.'],
    ['health','健康','けんこう','health; healthy',na,'健康のために毎日歩いています。','I walk every day for my health.'],
    ['exercise','運動','うんどう','exercise; physical activity',suru,'仕事の後、３０分ほど運動します。','I exercise for about thirty minutes after work.',true],
    ['sleep-health','睡眠','すいみん','sleep',suru,'最近は十分な睡眠が取れています。','Recently I have been getting enough sleep.'],
    ['nutrition','栄養','えいよう','nutrition; nourishment',noun,'栄養のバランスを考えて料理します。','I consider nutritional balance when cooking.'],
    ['tire','疲れる','つかれる','to become tired',ii,'長い時間歩くと疲れる。','I get tired when I walk for a long time.',true],
    ['rest','休む','やすむ','to rest; to take time off','godan verb (intransitive / transitive)','今日は仕事を休む。','I am taking the day off work today.',true],
    ['wound','傷','きず','wound; scratch',noun,'手の傷が少し痛みます。','The wound on my hand hurts a little.'],
    ['injury','けが','けが','injury',suru,'けがをした友人を病院に連れて行きました。','I took my injured friend to the hospital.'],
    ['emergency','救急','きゅうきゅう','emergency medical care',noun,'救急の入口は建物の裏にあります。','The emergency entrance is at the back of the building.'],
    ['recovery','回復','かいふく','recovery',suru,'休んだら、体力が回復しました。','My strength recovered after I rested.'],
  ],
  nature: [
    ['nature','自然','しぜん','nature; natural',na,'この町では豊かな自然を楽しめます。','You can enjoy abundant nature in this town.'],
    ['environment','環境','かんきょう','environment; surroundings',noun,'環境を守るため、ごみを減らしましょう。','Let us reduce waste to protect the environment.'],
    ['season','季節','きせつ','season',noun,'花が咲く季節が好きです。','I like the season when flowers bloom.'],
    ['air-temperature','気温','きおん','air temperature',noun,'午後は気温が３０度まで上がりました。','The temperature rose to thirty degrees in the afternoon.'],
    ['humidity','湿度','しつど','humidity',noun,'今日は湿度が高くて、蒸し暑いです。','Humidity is high today, and it is hot and muggy.'],
    ['sunlight','日差し','ひざし','sunlight; sunshine',noun,'強い日差しを避けて歩きました。','I walked out of the strong sunlight.'],
    ['shade','日陰','ひかげ','shade; shaded place',noun,'木の日陰で休みました。','I rested in the shade of a tree.'],
    ['typhoon','台風','たいふう','typhoon',noun,'台風が近づいているので、窓を閉めました。','A typhoon is approaching, so I closed the windows.'],
    ['thunder','雷','かみなり','thunder; lightning',noun,'遠くで雷の音が聞こえます。','I can hear thunder in the distance.'],
    ['earthquake','地震','じしん','earthquake',noun,'地震の後、家族の安全を確認しました。','After the earthquake, I checked that my family was safe.'],
    ['flood','洪水','こうずい','flood',noun,'大雨で洪水が起こりました。','The heavy rain caused a flood.'],
    ['plant','植物','しょくぶつ','plant; vegetation',noun,'窓の近くで植物を育てています。','I grow plants near the window.'],
    ['grass','草','くさ','grass; weeds',noun,'庭の草を取りました。','I pulled up the weeds in the garden.'],
    ['leaf','葉','は','leaf; leaves',noun,'秋になると、葉の色が変わります。','The leaves change color in autumn.'],
    ['branch','枝','えだ','branch; twig',noun,'木の枝に鳥が止まっています。','A bird is perched on a branch.'],
    ['root','根','ね','root',noun,'この木は根が深いです。','This tree has deep roots.'],
    ['seed','種','たね','seed',noun,'春に花の種をまきました。','I sowed flower seeds in spring.'],
    ['forest','森','もり','forest',noun,'森の中を静かに歩きました。','I walked quietly through the forest.'],
    ['coast','海岸','かいがん','coast; seashore',noun,'海岸で夕日を見ました。','I watched the sunset on the coast.'],
    ['lake','湖','みずうみ','lake',noun,'湖の周りを自転車で走りました。','I cycled around the lake.'],
    ['river','川','かわ','river',noun,'橋から川の水を見ました。','I looked at the river water from the bridge.',true],
    ['hill','丘','おか','hill',noun,'丘の上から町が見えます。','You can see the town from the top of the hill.'],
  ],
  technology: [
    ['machine','機械','きかい','machine; machinery',noun,'この機械は音が静かです。','This machine is quiet.'],
    ['operation','操作','そうさ','operation; handling a device',suru,'機械の操作を教えてください。','Please teach me how to operate the machine.'],
    ['settings','設定','せってい','settings; configuration',suru,'画面の明るさの設定を変えました。','I changed the screen-brightness setting.'],
    ['screen','画面','がめん','screen; display',noun,'画面の文字を大きくしました。','I made the text on the screen larger.'],
    ['power','電源','でんげん','power supply; power switch',noun,'使い終わったら、電源を切ってください。','Please turn off the power when you finish using it.'],
    ['battery','電池','でんち','battery',noun,'時計の電池を交換しました。','I replaced the clock battery.'],
    ['charging','充電','じゅうでん','charging a battery',suru,'出かける前に携帯電話を充電します。','I charge my phone before going out.'],
    ['connection','接続','せつぞく','connection',suru,'インターネットの接続が切れました。','The internet connection dropped.'],
    ['communication-tech','通信','つうしん','communication; transmission',suru,'山の中では通信が不安定でした。','The connection was unstable in the mountains.'],
    ['save','保存','ほぞん','saving; preservation',suru,'書いた文書を保存しました。','I saved the document I wrote.'],
    ['delete','削除','さくじょ','deletion; removing',suru,'必要のない写真を削除しました。','I deleted photos I did not need.'],
    ['search','検索','けんさく','search; looking up',suru,'住所を地図のアプリで検索しました。','I searched for the address in a map app.'],
    ['input','入力','にゅうりょく','input; entering data',suru,'名前と住所を入力してください。','Please enter your name and address.'],
    ['output','出力','しゅつりょく','output; producing data',suru,'計算の結果を紙に出力しました。','I output the calculation results on paper.'],
    ['printing','印刷','いんさつ','printing',suru,'会議の資料を２０枚印刷しました。','I printed twenty copies of the meeting handout.'],
    ['breakdown','故障','こしょう','breakdown; malfunction',suru,'エアコンの故障で部屋が暑いです。','The room is hot because the air conditioner has broken down.'],
    ['update','更新','こうしん','update; renewal',suru,'アプリの更新に５分かかりました。','Updating the app took five minutes.'],
    ['record','記録','きろく','record; recording',suru,'毎日の歩数を記録しています。','I record my daily step count.'],
    ['information','情報','じょうほう','information',noun,'駅の情報をウェブサイトで調べました。','I looked up station information on the website.'],
    ['function','機能','きのう','function; capability',suru,'このカメラには便利な機能があります。','This camera has useful features.'],
    ['device','装置','そうち','device; apparatus',noun,'安全のための装置を取り付けました。','I installed a safety device.'],
    ['mobile-phone','携帯電話','けいたいでんわ','mobile phone',noun,'携帯電話を家に忘れました。','I left my mobile phone at home.',true],
  ],
  community: [
    ['region','地域','ちいき','region; local area',noun,'この地域には公園が多いです。','There are many parks in this area.'],
    ['neighborhood','近所','きんじょ','neighborhood; vicinity',noun,'近所に新しい店ができました。','A new shop has opened in the neighborhood.'],
    ['resident','住民','じゅうみん','resident',noun,'住民が集まって町のことを話しました。','The residents gathered to discuss the town.'],
    ['citizen','市民','しみん','city resident; citizen',noun,'市民はこの施設を安く利用できます。','City residents can use this facility at a reduced price.'],
    ['neighborhood-association','自治会','じちかい','neighborhood association',noun,'自治会の集まりで自己紹介しました。','I introduced myself at the neighborhood association meeting.'],
    ['activity','活動','かつどう','activity; being active',suru,'地域の活動に参加しています。','I take part in community activities.'],
    ['event','行事','ぎょうじ','event; organized occasion',noun,'学校の行事に家族で参加しました。','My family attended a school event.'],
    ['gathering','集会','しゅうかい','meeting; gathering',suru,'日曜日に住民の集会があります。','There is a residents’ meeting on Sunday.'],
    ['cooperation','協力','きょうりょく','cooperation',suru,'みんなで協力して会場を片付けました。','Everyone worked together to tidy up the venue.'],
    ['donation','寄付','きふ','donation',suru,'使わなくなった本を図書館に寄付しました。','I donated books I no longer used to the library.'],
    ['consultation','相談','そうだん','consultation; discussing a concern',suru,'困ったときは先生に相談します。','I consult the teacher when I have a problem.'],
    ['disaster-prevention','防災','ぼうさい','disaster preparedness and prevention',noun,'防災の訓練に参加しました。','I took part in a disaster-preparedness drill.'],
    ['evacuation','避難','ひなん','evacuation; taking refuge',suru,'台風のため、安全な場所に避難しました。','I evacuated to a safe place because of the typhoon.'],
    ['clean-up','清掃','せいそう','cleaning; cleanup',suru,'地域の清掃に参加しました。','I took part in a neighborhood cleanup.'],
    ['public','公共','こうきょう','public; shared by the community',noun,'公共の場所では静かにしましょう。','Let us be quiet in public places.'],
    ['facility','施設','しせつ','facility; institution',noun,'この施設には体育館があります。','This facility has a gymnasium.'],
    ['park','公園','こうえん','park',noun,'近くの公園で散歩しました。','I took a walk in a nearby park.',true],
    ['square','広場','ひろば','open square; plaza',noun,'駅前の広場で友人を待ちました。','I waited for a friend in the square in front of the station.'],
    ['government-office','役所','やくしょ','government office; municipal office',noun,'住所の変更のために役所へ行きました。','I went to the municipal office to register a change of address.'],
    ['vote','投票','とうひょう','voting; ballot',suru,'市の選挙で投票しました。','I voted in the municipal election.'],
    ['election','選挙','せんきょ','election',suru,'選挙の結果がニュースで発表されました。','The election results were announced on the news.'],
    ['rule','規則','きそく','rule; regulation',noun,'施設の規則を守ってください。','Please follow the facility’s rules.'],
  ],
  culture: [
    ['culture','文化','ぶんか','culture',noun,'日本の文化について本で調べました。','I researched Japanese culture in books.'],
    ['tradition','伝統','でんとう','tradition',noun,'この町には長い伝統があります。','This town has a long tradition.'],
    ['festival','祭り','まつり','festival',noun,'夏の祭りで屋台の料理を食べました。','I ate food from stalls at the summer festival.',true],
    ['art','芸術','げいじゅつ','art; the arts',noun,'週末に芸術についての講座を受けました。','I took a course about art over the weekend.'],
    ['artwork','作品','さくひん','work of art; creative work',noun,'学生の作品が廊下に並んでいます。','Students’ artworks are displayed in the hallway.'],
    ['performance','演奏','えんそう','musical performance',suru,'友人のピアノの演奏を聞きました。','I listened to my friend’s piano performance.'],
    ['stage','舞台','ぶたい','stage; setting',noun,'舞台の上に俳優が出てきました。','An actor came onto the stage.'],
    ['play','劇','げき','play; drama',noun,'学校の劇で母親の役を演じました。','I played a mother in the school play.'],
    ['novel','小説','しょうせつ','novel',noun,'電車の中で小説を読んでいます。','I read novels on the train.'],
    ['poem','詩','し','poem; poetry',noun,'自分の気持ちを短い詩にしました。','I expressed my feelings in a short poem.'],
    ['painting','絵画','かいが','painting; paintings',noun,'美術館で絵画を見ました。','I saw paintings at the art museum.'],
    ['photo','写真','しゃしん','photograph',noun,'旅行の写真を家族に見せました。','I showed my family photos from the trip.',true],
    ['photography','撮影','さつえい','photography; filming',suru,'この場所では撮影が禁止されています。','Photography is prohibited here.'],
    ['display','展示','てんじ','display; exhibition',suru,'図書館で古い地図の展示をしています。','Old maps are on display at the library.'],
    ['exhibition','展覧会','てんらんかい','exhibition',noun,'週末に友人の展覧会へ行きました。','I went to my friend’s exhibition over the weekend.'],
    ['appreciation','鑑賞','かんしょう','viewing or listening with appreciation',suru,'休日は映画の鑑賞を楽しんでいます。','I enjoy watching films on my days off.'],
    ['costume','衣装','いしょう','costume; performance clothes',noun,'劇で使う衣装を作っています。','We are making costumes for the play.'],
    ['instrument','楽器','がっき','musical instrument',noun,'楽器を習ってみたいです。','I would like to try learning a musical instrument.'],
    ['dance','踊る','おどる','to dance',gi,'祭りで友人と一緒に踊る。','I dance with friends at the festival.'],
    ['invitation','招待','しょうたい','invitation; inviting someone',suru,'友人を誕生日の食事に招待しました。','I invited a friend to a birthday meal.'],
    ['celebrate','祝う','いわう','to celebrate; to congratulate',gt,'家族で妹の卒業を祝う。','Our family celebrates my younger sister’s graduation.'],
    ['commemoration','記念','きねん','commemoration; souvenir marking an occasion',suru,'旅行の記念に写真を撮りました。','I took a photo to remember the trip.'],
  ],
  feelings: [
    ['relief','安心','あんしん','relief; peace of mind',suru,'無事に着いたと聞いて、安心しました。','I felt relieved when I heard they had arrived safely.'],
    ['worry','心配','しんぱい','worry; concern',na,'帰りが遅い弟のことが心配です。','I am worried about my younger brother, who is late coming home.'],
    ['anxiety','不安','ふあん','anxiety; uneasy',na,'初めての仕事なので、不安があります。','I feel anxious because it is my first job.'],
    ['nervousness','緊張','きんちょう','nervousness; tension',suru,'面接の前は緊張しました。','I was nervous before the interview.'],
    ['satisfaction','満足','まんぞく','satisfaction; being satisfied',suru,'ホテルのサービスに満足しました。','I was satisfied with the hotel service.'],
    ['dissatisfaction','不満','ふまん','dissatisfaction; discontented',na,'説明が足りないことに不満があります。','I am dissatisfied with the lack of explanation.'],
    ['regrettable','残念','ざんねん','disappointing; regrettable',na,'旅行に行けなくて、残念です。','I am disappointed that I cannot go on the trip.'],
    ['moved','感動','かんどう','being deeply moved',suru,'映画の最後の場面に感動しました。','I was moved by the film’s final scene.'],
    ['joy','喜び','よろこび','joy; delight',noun,'合格の喜びを家族と分かち合いました。','I shared the joy of passing with my family.'],
    ['sadness','悲しみ','かなしみ','sadness; sorrow',noun,'友人と話して、悲しみが少し軽くなりました。','Talking to a friend eased my sadness a little.'],
    ['anger','怒り','いかり','anger',noun,'怒りを感じても、落ち着いて話しましょう。','Even when we feel angry, let us speak calmly.'],
    ['lonely','寂しい','さびしい','lonely; feeling the absence of someone',adjective,'友人が引っ越して、寂しいです。','I feel lonely because my friend moved away.'],
    ['embarrassed','恥ずかしい','はずかしい','embarrassed; embarrassing',adjective,'名前を間違えて、恥ずかしいです。','I am embarrassed because I got the name wrong.'],
    ['nostalgic','懐かしい','なつかしい','nostalgic; fondly remembered',adjective,'この歌を聞くと、子どものころが懐かしいです。','This song makes me feel nostalgic for my childhood.'],
    ['surprised','驚く','おどろく','to be surprised',gi,'急に大きな音がすると驚く。','I get startled by a sudden loud sound.'],
    ['rejoice','喜ぶ','よろこぶ','to be glad; to rejoice','godan verb (transitive / intransitive uses)','友人からの手紙を読むと、母は喜ぶ。','My mother is delighted when she reads letters from friends.'],
    ['be-troubled','悩む','なやむ','to worry over; to struggle with a problem',gi,'どの仕事を選ぶか悩む。','I struggle to decide which job to choose.'],
    ['calm-down','落ち着く','おちつく','to calm down; to settle',gi,'深く息を吸うと、気持ちが落ち着く。','Taking a deep breath calms me down.'],
    ['endurance','我慢','がまん','endurance; putting up with something',suru,'暑さを我慢せずに、冷房を使いました。','I used the air conditioning instead of putting up with the heat.'],
    ['hope','希望','きぼう','hope; wish',suru,'将来への希望を持っています。','I have hope for the future.'],
    ['confidence','自信','じしん','self-confidence',noun,'何度も練習して、自信がつきました。','Practicing repeatedly helped me gain confidence.'],
    ['courage','勇気','ゆうき','courage',noun,'初めて一人で旅行するには勇気が必要でした。','It took courage to travel alone for the first time.'],
  ],
  communication: [
    ['conversation','会話','かいわ','conversation',suru,'友人との会話を楽しみました。','I enjoyed talking with my friend.'],
    ['opinion','意見','いけん','opinion; view',noun,'自分の意見を会議で伝えました。','I expressed my opinion at the meeting.'],
    ['explanation','説明','せつめい','explanation',suru,'先生の説明は分かりやすいです。','The teacher’s explanations are easy to understand.'],
    ['question','質問','しつもん','question; asking a question',suru,'分からないことを先生に質問しました。','I asked the teacher about something I did not understand.',true],
    ['reply','返事','へんじ','reply; answer',suru,'友人から返事が来ました。','I received a reply from my friend.',true],
    ['reply-message','返信','へんしん','reply to a written message',suru,'メールの返信が遅れてしまいました。','I was late replying to the email.'],
    ['convey','伝える','つたえる','to convey; to tell',it,'変更した時間をみんなに伝える。','I tell everyone the new time.'],
    ['ask','尋ねる','たずねる','to ask; to inquire',it,'受付で会場の場所を尋ねる。','I ask at reception where the venue is.'],
    ['discuss','話し合う','はなしあう','to discuss with one another','godan verb (transitive; reciprocal)','家族で旅行の計画を話し合う。','Our family discusses the travel plans.'],
    ['inform','知らせる','しらせる','to inform; to let someone know',it,'結果が分かったら、すぐに知らせる。','I will let you know as soon as I have the result.'],
    ['decline','断る','ことわる','to decline; to refuse',gt,'予定があるので、誘いを断る。','I decline the invitation because I already have plans.'],
    ['apologize','謝る','あやまる','to apologize',gi,'遅れたことを友人に謝る。','I apologize to my friend for being late.'],
    ['request','頼む','たのむ','to request; to ask a favor',gt,'忙しいので、友人に手伝いを頼む。','I ask a friend to help because I am busy.',true],
    ['invite','誘う','さそう','to invite someone to join',gt,'友人を映画に誘う。','I invite a friend to the movies.'],
    ['promise','約束','やくそく','promise; arrangement',suru,'友人との約束を忘れていました。','I had forgotten my arrangement with a friend.',true],
    ['misunderstanding','誤解','ごかい','misunderstanding',suru,'説明を聞いて、誤解がなくなりました。','Hearing the explanation cleared up the misunderstanding.'],
    ['rumor','うわさ','うわさ','rumor; gossip',noun,'そのうわさが本当かどうか分かりません。','I do not know whether that rumor is true.'],
    ['expression','表現','ひょうげん','expression; way of expressing',suru,'丁寧な表現を使うようにしています。','I make a point of using polite expressions.'],
    ['attitude','態度','たいど','attitude; manner',noun,'店員の親切な態度が印象に残りました。','The staff member’s kind manner left an impression on me.'],
    ['polite','丁寧','ていねい','polite; careful',na,'店員が丁寧に説明してくれました。','The staff member explained it politely and carefully.'],
    ['rudeness','失礼','しつれい','rudeness; impolite',na,'話の途中で帰って、失礼しました。','I was rude to leave in the middle of the conversation.'],
    ['honorific-language','敬語','けいご','honorific and polite language',noun,'仕事で使う敬語を練習しています。','I practice the polite language I use at work.'],
  ],
  time: [
    ['recently','最近','さいきん','recently; lately','noun / adverb','最近、早く寝るようにしています。','Recently, I have been making a point of going to bed early.'],
    ['previously','以前','いぜん','before; previously','noun / adverb','以前は駅から遠い所に住んでいました。','I used to live far from the station.'],
    ['from-now','今後','こんご','from now on; in the future','noun / adverb','今後はもっと早く連絡します。','I will contact you earlier from now on.'],
    ['present','現在','げんざい','at present; current time','noun / adverb','現在、この部屋は使われていません。','This room is not being used at present.'],
    ['future','将来','しょうらい','future','noun / adverb','将来は自分の店を開きたいです。','I want to open my own shop in the future.'],
    ['past','過去','かこ','past',noun,'過去の記録を調べました。','I examined past records.'],
    ['on-way','途中','とちゅう','on the way; partway through',noun,'帰る途中で雨が降り始めました。','It started raining on my way home.'],
    ['just-before','直前','ちょくぜん','just before; immediately before',noun,'出発の直前に電話が来ました。','I received a call just before departure.'],
    ['just-after','直後','ちょくご','just after; immediately after',noun,'授業の直後に先生に質問しました。','I asked the teacher a question right after class.'],
    ['time-limit','期限','きげん','time limit; deadline',noun,'本の返却期限は来週の月曜日です。','The deadline for returning the book is next Monday.'],
    ['period','期間','きかん','period; length of time',noun,'工事の期間は２週間です。','The construction period is two weeks.'],
    ['instant','瞬間','しゅんかん','moment; instant',noun,'ドアを開けた瞬間、風が入りました。','Wind came in the instant I opened the door.'],
    ['morning-time','午前','ごぜん','morning; a.m.',noun,'午前の授業は１１時に終わります。','The morning classes finish at eleven.',true],
    ['afternoon-time','午後','ごご','afternoon; p.m.',noun,'午後は図書館で勉強します。','I will study at the library in the afternoon.',true],
    ['weekday','平日','へいじつ','weekday',noun,'平日は午前９時から働いています。','I work from nine in the morning on weekdays.'],
    ['day-off','休日','きゅうじつ','day off; holiday',noun,'休日は友人と会うことが多いです。','I often meet friends on my days off.'],
    ['following-day','翌日','よくじつ','following day; next day',noun,'荷物は注文した翌日に届きました。','The package arrived the day after I ordered it.'],
    ['previous-day','前日','ぜんじつ','previous day; day before',noun,'試験の前日は早く寝ました。','I went to bed early the day before the exam.'],
    ['every-time','毎回','まいかい','every time; each occasion','noun / adverb','毎回、同じ時間に授業が始まります。','Class starts at the same time each session.'],
    ['on-day','当日','とうじつ','the day of an event; that same day',noun,'当日は受付で名前を言ってください。','On the day of the event, please give your name at reception.'],
    ['once','一度','いちど','once; one time','noun / adverb','説明をもう一度聞きました。','I listened to the explanation once more.',true],
    ['a-while','しばらく','しばらく','for a while; a short period','adverb','雨がやむまで、しばらく待ちます。','I will wait a while until the rain stops.'],
  ],
  services: [
    ['procedure','手続き','てつづき','procedure; formalities',noun,'引っ越しの手続きに役所へ行きました。','I went to the municipal office for moving-related procedures.'],
    ['application','申請','しんせい','formal application; request',suru,'休暇の申請を出しました。','I submitted a leave application.'],
    ['certificate','証明書','しょうめいしょ','certificate; documentary proof',noun,'学校で卒業の証明書をもらいました。','I received a graduation certificate from the school.'],
    ['identity-document','身分証明書','みぶんしょうめいしょ','identity document',noun,'受付で身分証明書を見せました。','I showed my identity document at reception.'],
    ['service-counter','窓口','まどぐち','service counter; contact point',noun,'窓口で申請書をもらいました。','I got an application form at the service counter.'],
    ['bank-account','口座','こうざ','bank account',noun,'給料はこの口座に入ります。','My salary is paid into this account.'],
    ['deposit','預金','よきん','bank deposit; deposited savings',suru,'銀行の預金を少し増やしました。','I increased my bank savings a little.'],
    ['withdraw','引き出す','ひきだす','to withdraw; to pull out',gt,'銀行で現金を引き出す。','I withdraw cash at the bank.'],
    ['bank-transfer','振り込む','ふりこむ','to transfer money into an account',gt,'家賃を指定の口座に振り込む。','I transfer the rent to the designated account.'],
    ['money-exchange','両替','りょうがえ','exchanging money',suru,'旅行の前に銀行で両替しました。','I exchanged money at the bank before my trip.'],
    ['insurance','保険','ほけん','insurance',noun,'旅行の保険に入りました。','I took out travel insurance.'],
    ['delivery','配達','はいたつ','delivery',suru,'荷物の配達は午後の予定です。','The package is scheduled for delivery in the afternoon.'],
    ['mail','郵便','ゆうびん','mail; postal service',noun,'郵便で書類を送りました。','I sent the documents by post.'],
    ['postage','送料','そうりょう','shipping charge; postage',noun,'商品の価格に送料は含まれていません。','The shipping charge is not included in the product price.'],
    ['lend','貸す','かす','to lend',gt,'友人に辞書を貸す。','I lend my dictionary to a friend.',true],
    ['borrow','借りる','かりる','to borrow; to rent',it,'図書館で本を借りる。','I borrow books from the library.',true],
    ['leave-in-care','預ける','あずける','to leave something in someone’s care',it,'駅の受付に荷物を預ける。','I leave my luggage at the station’s reception desk.'],
    ['receive','受け取る','うけとる','to receive; to accept',gt,'受付で予約した本を受け取る。','I collect the book I reserved at reception.'],
    ['customer','客','きゃく','customer; guest',noun,'店の前で客が待っています。','Customers are waiting in front of the shop.',true],
    ['staff-member','係','かかり','person in charge; staff member',noun,'入口の係に場所を聞きました。','I asked the staff member at the entrance where it was.'],
    ['hair-salon','美容院','びよういん','hair salon',noun,'美容院で髪を切ってもらいました。','I had my hair cut at a salon.'],
    ['laundry','洗濯','せんたく','laundry; washing clothes',suru,'晴れた日に洗濯をします。','I do the laundry on sunny days.',true],
  ],
};

const extensionSlugs = new Set(['getting-ready', 'bedtime', 'rising', 'prescription', 'neighborhood-association', 'appreciation', 'evacuation', 'identity-document']);
export const expandedVocabulary: LexicalEntry[] = Object.entries(rows).flatMap(([topicId, entries]) => entries.map(([slug, word, reading, meaning, wordClass, example, exampleTranslation, review]) => ({
  id: `vx-${topicId}-${slug}`, word, reading, meaning, wordClass, example, exampleTranslation,
  topicId: topicId as Topic, level: (review ? 'review' : extensionSlugs.has(slug) ? 'extension' : 'N3-style') as Level,
})));

// Character meanings are deliberately brief memory cues. Readings are taught
// through actual linked words; these are not context-free kanji reading tests.
const characterMeanings: [string, string][] = [
  ['起','rise; begin'],['寝','sleep'],['洗','wash'],['磨','polish'],['着','wear; arrive'],['替','replace'],['片','one side; piece'],['付','attach'],['済','finish; settle'],['過','pass; exceed'],['習','learn; practice'],['慣','habit; become accustomed'],['日','day; sun'],['常','usual'],['外','outside'],['出','go out'],['散','scatter'],['歩','walk'],['休','rest'],['憩','rest'],['用','use'],['事','matter; thing'],['就','undertake; take a position'],['目','eye'],['覚','remember; awaken'],['手','hand'],['歯','tooth'],['身','body'],['支','support'],['度','degree; occasion'],['順','order'],['番','turn; number'],['昼','daytime; noon'],
  ['家','house; family'],['族','family; group'],['親','parent; close'],['戚','relative'],['夫','husband'],['婦','woman; wife'],['妻','wife'],['息','breath'],['子','child'],['娘','daughter'],['祖','ancestor'],['父','father'],['母','mother'],['孫','grandchild'],['兄','older brother'],['弟','younger brother'],['姉','older sister'],['妹','younger sister'],['友','friend'],['人','person'],['同','same'],['僚','colleague'],['上','above; up'],['司','administer'],['先','before; ahead'],['輩','companion; generation'],['後','after; behind'],['隣','neighbor'],['知','know'],['合','fit; join'],['仲','relationship; companionship'],['相','mutual; appearance'],['世','world; generation'],['話','talk'],['性','nature; character'],['格','status; standard'],
  ['部','section; part'],['屋','roof; building'],['玄','deep; profound'],['関','barrier; connection'],['廊','corridor'],['下','below; down'],['台','stand; platform'],['所','place'],['居','reside'],['室','room'],['床','floor; bed'],['壁','wall'],['天','sky; heaven'],['井','well'],['窓','window'],['根','root'],['階','storey; rank'],['段','step; level'],['具','tool; equipment'],['棚','shelf'],['引','pull'],['鏡','mirror'],['毛','hair; fur'],['布','cloth'],['団','group'],['暖','warm'],['房','room'],['冷','cold'],['賃','rent; charge'],['越','cross; exceed'],['掃','sweep'],['除','remove'],
  ['値','value'],['価','price; value'],['格','status; standard'],['商','trade'],['品','goods; quality'],['物','thing'],['売','sell'],['場','place'],['払','pay; brush away'],['現','present; appear'],['金','gold; money'],['釣','fish; change'],['割','divide; proportion'],['半','half'],['額','amount; forehead'],['返','return'],['交','exchange; intersect'],['換','exchange'],['切','cut'],['在','exist'],['庫','warehouse'],['注','pour; attention'],['文','writing; sentence'],['袋','bag'],['箱','box'],['包','wrap'],['装','dress; equip'],['算','calculate'],['質','quality; substance'],['量','quantity'],['試','test; try'],['特','special'],
  ['食','eat'],['朝','morning'],['夕','evening'],['材','material'],['料','material; charge'],['調','adjust; investigate'],['味','taste'],['塩','salt'],['砂','sand'],['糖','sugar'],['油','oil'],['野','field'],['菜','vegetable'],['果','fruit; result'],['卵','egg'],['肉','meat'],['魚','fish'],['焼','burn; cook with dry heat'],['煮','boil; simmer'],['蒸','steam'],['揚','raise; deep-fry'],['混','mix'],
  ['旅','journey'],['行','go; carry out'],['観','observe'],['光','light'],['目','eye'],['的','target; -like'],['地','ground; place'],['宿','lodge; stay'],['泊','stay overnight'],['館','building'],['約','promise; approximately'],['滞','stagnate; stay'],['発','depart; emit'],['到','arrive'],['案','plan'],['内','inside'],['土','earth'],['産','produce'],['景','scenery'],['色','color'],['図','diagram; plan'],['迷','lose one’s way; hesitate'],['荷','baggage; burden'],['客','guest; customer'],['名','name'],['海','sea'],['国','country'],['帰','return home'],['費','cost'],
  ['通','pass; communicate'],['運','carry; fortune'],['乗','ride'],['往','go; outward journey'],['復','return; repeat'],['終','end'],['電','electricity'],['始','begin'],['時','time'],['刻','carve; moment'],['表','express; surface'],['改','change; reform'],['札','ticket; note'],['符','token; sign'],['定','fix; decide'],['期','period'],['券','ticket'],['停','stop'],['留','remain'],['渋','astringent; hesitant'],['駐','station; park'],['車','vehicle'],['降','descend'],['横','sideways'],['断','cut off; refuse'],['道','path; way'],['信','trust'],['号','number; sign'],['差','difference'],['点','point'],['線','line'],['路','road'],['勤','work'],
  ['会','meet'],['議','discuss'],['職','job'],['給','supply'],['残','remain'],['業','business'],['暇','free time'],['書','write'],['類','kind; category'],['報','report'],['告','tell'],['担','carry; undertake'],['当','hit; concerned'],['面','face; surface'],['接','connect'],['転','turn'],['退','withdraw'],['作','make'],['務','duty'],['責','responsibility'],['任','entrust'],['経','pass through; manage'],['験','test'],['提','present'],['取','take'],['契','pledge; contract'],['研','polish; study'],['評','evaluate'],
  ['授','give; teach'],['講','lecture'],['成','become'],['績','achievement'],['不','not'],['学','learn'],['究','investigate'],['課','lesson; assign'],['題','topic'],['専','special; exclusive'],['門','gate'],['進','advance'],['卒','graduate'],['教','teach'],['科','department; field'],['辞','word; resign'],['理','reason; principle'],['解','untie; understand'],['入','enter'],
  ['症','symptom'],['状','form; condition'],['痛','pain'],['熱','heat; fever'],['咳','cough'],['頭','head'],['腹','belly'],['風','wind'],['邪','evil; harmful'],['診','examine medically'],['察','inspect'],['治','govern; heal'],['療','medical treatment'],['薬','medicine'],['処','deal with'],['方','direction; method'],['箋','paper; written note'],['体','body'],['温','warm'],['健','healthy'],['康','healthy; peaceful'],['動','move'],['睡','sleep'],['眠','sleep'],['栄','prosper'],['養','nourish'],['疲','tired'],['傷','wound'],['救','save'],['急','hurry; urgent'],['回','return; times'],
  ['自','self'],['然','so; natural state'],['環','ring; surrounding'],['境','border; environment'],['季','season'],['節','section; season'],['気','air; spirit'],['湿','damp'],['陰','shade'],['太','large; thick'],['雷','thunder'],['震','shake'],['洪','flood'],['水','water'],['植','plant'],['草','grass'],['葉','leaf'],['枝','branch'],['種','seed; kind'],['森','forest'],['岸','shore'],['湖','lake'],['川','river'],['丘','hill'],
  ['機','machine; opportunity'],['械','device'],['操','operate'],['設','establish'],['画','picture'],['源','source'],['池','pond'],['充','fill'],['連','connect'],['存','exist; preserve'],['削','scrape; delete'],['検','examine'],['索','search; cord'],['力','power'],['印','mark; seal'],['刷','print'],['故','reason; old'],['障','obstacle'],['更','renew'],['新','new'],['記','record'],['録','record'],['情','emotion; information'],['能','ability'],['置','place'],['携','carry'],['帯','belt; carry'],
  ['域','area'],['近','near'],['住','reside'],['民','people'],['市','city; market'],['活','active; live'],['集','gather'],['協','cooperate'],['寄','approach; send'],['防','prevent'],['災','disaster'],['避','avoid'],['難','difficult'],['清','clear; clean'],['公','public'],['共','together'],['広','broad'],['役','service; role'],['投','throw; cast'],['票','ballot; ticket'],['選','select'],['挙','raise'],['規','rule'],['則','law; rule'],
  ['化','change; -ization'],['伝','transmit'],['統','unify'],['祭','festival'],['芸','art'],['術','technique'],['演','perform'],['奏','play music'],['舞','dance'],['劇','drama'],['小','small'],['説','explain'],['詩','poem'],['絵','picture'],['撮','photograph'],['示','show'],['展','unfold; exhibit'],['覧','view'],['鑑','examine; model'],['賞','prize; appreciate'],['衣','clothing'],['楽','pleasant; music'],['器','vessel; instrument'],['踊','dance'],['招','invite'],['待','wait'],['祝','celebrate'],['念','thought'],
  ['安','peace; inexpensive'],['心','heart'],['配','distribute'],['緊','tight'],['張','stretch'],['満','full'],['足','foot; sufficient'],['感','feel'],['喜','joy'],['悲','sad'],['怒','anger'],['寂','lonely; quiet'],['恥','shame'],['懐','nostalgia; bosom'],['驚','surprise'],['悩','worry'],['落','fall'],['我','self'],['慢','slack; conceited'],['希','hope; rare'],['望','hope; look'],['勇','brave'],
  ['意','intention; meaning'],['見','see'],['明','bright; clear'],['問','ask'],['送','send'],['尋','seek; inquire'],['談','talk'],['謝','thank; apologize'],['頼','rely; request'],['誘','invite'],['束','bundle'],['誤','mistake'],['態','condition; manner'],['丁','block; care'],['寧','peaceful; careful'],['失','lose'],['礼','courtesy'],['敬','respect'],['語','language'],
  ['最','most'],['前','front; before'],['今','now'],['将','future; leader'],['来','come'],['去','leave; past'],['途','route'],['中','middle'],['直','straight; direct'],['限','limit'],['瞬','blink; instant'],['午','noon'],['平','flat; even'],['翌','next'],['毎','each'],['一','one'],
  ['申','say; apply'],['請','request'],['証','proof'],['分','part; divide'],['口','mouth; opening'],['座','seat'],['預','deposit; entrust'],['振','shake'],['込','enter into'],['両','both'],['保','protect'],['険','danger; steep'],['達','reach; achieve'],['郵','mail'],['便','convenient; delivery'],['貸','lend'],['借','borrow'],['受','receive'],['係','person in charge; connection'],['美','beautiful'],['容','contain; appearance'],['院','institution'],['濯','wash'],
];

const legacyCharacters = new Set(['予','変','参','絡','準','確','遅','届','続','間','減','修']);
const seenCharacters = new Set<string>();
export const expandedKanji: (Kanji & { topicId: Topic })[] = characterMeanings.flatMap(([character, meaning]) => {
  if (legacyCharacters.has(character) || seenCharacters.has(character)) return [];
  const words = expandedVocabulary.filter(word => word.word.includes(character));
  if (!words.length) return [];
  seenCharacters.add(character);
  return [{ id: `kx-${character.codePointAt(0)!.toString(16)}`, character, meaning, wordIds: words.map(word => word.id), topicId: words[0].topicId }];
});

type Choice = { text: string; explanation: string; correct?: boolean };
function question(id: string, type: LexicalQuestion['questionType'], word: LexicalEntry, prompt: string, choices: Choice[], rotation = 0): LexicalQuestion {
  if (choices.length !== 4 || new Set(choices.map(choice => choice.text.normalize('NFKC'))).size !== 4 || choices.filter(choice => choice.correct).length !== 1) throw new Error(`Invalid lexical choices: ${id}`);
  const rotated = [...choices.slice(rotation % 4), ...choices.slice(0, rotation % 4)];
  const options = rotated.map((choice, index) => ({ id: `${id}-${'abcd'[index]}`, text: choice.text }));
  return { id, skill: type === 'kanji-reading' ? 'kanji' : 'vocabulary', questionType: type, topicId: word.topicId, vocabularyId: word.id, prompt,
    options, correctOptionId: options[rotated.findIndex(choice => choice.correct)].id,
    explanations: Object.fromEntries(options.map((option, index) => [option.id, rotated[index].explanation])),
  };
}

// Distractors use reviewed words, not guessed alternative pronunciations. A
// different spelling with the same reading is excluded from orthography items.
function distractors(word: LexicalEntry): LexicalEntry[] {
  const ranked = expandedVocabulary.filter(candidate => candidate.word !== word.word && candidate.reading !== word.reading).map((candidate, index) => {
    const proximity = Math.abs(candidate.reading.length - word.reading.length)
      - (candidate.wordClass === word.wordClass ? 3 : 0)
      - (candidate.reading[0] === word.reading[0] ? 2 : 0)
      - (candidate.topicId === word.topicId ? 1 : 0);
    return { candidate, proximity, index };
  }).sort((a, b) => a.proximity - b.proximity || a.index - b.index);
  const result: LexicalEntry[] = [];
  for (const { candidate } of ranked) {
    if (!result.some(existing => existing.reading === candidate.reading || existing.word === candidate.word)) result.push(candidate);
    if (result.length === 3) break;
  }
  if (result.length !== 3) throw new Error(`Insufficient distractors for ${word.id}`);
  return result;
}

const readingQuestions = expandedVocabulary.filter(word => /\p{Script=Han}/u.test(word.word)).map((word, index) => question(
  `qx-reading-${word.id.slice(3)}`, 'kanji-reading', word,
  `「${word.word}」の読み方はどれですか。\n例文：${word.example}`,
  [{ text: word.reading, correct: true, explanation: `In this sentence, 「${word.word}」 is read ${word.reading}. It means “${word.meaning}.”` },
    ...distractors(word).map(other => ({ text: other.reading, explanation: `${other.reading} is the reading of 「${other.word}」 (${other.meaning}), not 「${word.word}」 in this sentence. The required reading is ${word.reading}.` }))], index % 4,
));

const orthographyQuestions = expandedVocabulary.filter((word, index) => index % 2 === 0 && /\p{Script=Han}/u.test(word.word) && word.example.includes(word.word)).map((word, index) => question(
  `qx-spelling-${word.id.slice(3)}`, 'orthography', word,
  `【　】の言葉の正しい表記はどれですか。\n${word.example.replace(word.word, `【${word.reading}】`)}`,
  [{ text: word.word, correct: true, explanation: `The spelling is 「${word.word}」, read ${word.reading}. It means “${word.meaning},” which fits this sentence.` },
    ...distractors(word).map(other => ({ text: other.word, explanation: `「${other.word}」 is read ${other.reading} and means “${other.meaning}.” It does not match the requested reading ${word.reading} in this sentence.` }))], (index + 1) % 4,
));

const lexicon = new Map(expandedVocabulary.map(word => [word.id, word]));
function authored(id: string, type: LexicalQuestion['questionType'], wordId: string, prompt: string, texts: [string,string,string,string], correct: 0|1|2|3, reasons: [string,string,string,string]): LexicalQuestion {
  const word = lexicon.get(wordId);
  if (!word) throw new Error(`Missing lexical reference ${wordId}`);
  return question(id, type, word, prompt, texts.map((text, index) => ({ text, explanation: reasons[index], correct: index === correct })));
}

const authoredQuestions: LexicalQuestion[] = [
  authored('qx-context-rent','vocabulary-context','vx-home-rent','この部屋の（　）は、毎月６万円です。',['家賃','天井','毛布','廊下'],0,
    ['家賃 is rent for a residence. 毎月６万円 gives its monthly amount.','天井 is a ceiling, not a monthly payment.','毛布 is a blanket; it does not name the monthly cost of living in a room.','廊下 is a hallway. It is not an amount due each month.']),
  authored('qx-context-cash','vocabulary-context','vx-shopping-cash','この店ではカードが使えません。（　）で払ってください。',['品質','予算','現金','在庫'],2,
    ['品質 means product quality, not a method of paying.','予算 is a budget. It does not name the money handed over at the counter.','現金 is cash. If cards are not accepted, 現金で払う is the stated alternative.','在庫 means stock. Merchandise in stock is not a payment method.']),
  authored('qx-context-transfer','vocabulary-context','vx-transport-transfer','この電車で終点まで行って、そこで別の電車に乗ってください。（　）が１回必要です。',['乗り換え','駐車','渋滞','遅刻'],0,
    ['乗り換え means changing vehicles. Taking a different train at the terminus requires one transfer.','駐車 means parking a vehicle. The passenger is changing trains, not parking a vehicle.','渋滞 is traffic congestion. Changing trains does not require a traffic jam.','遅刻 means arriving late. The passage does not say the passenger needs to arrive late.']),
  authored('qx-context-deadline','vocabulary-context','vx-time-time-limit','この本は来週の月曜日までに返してください。返却の（　）を過ぎないようにしましょう。',['気温','途中','期限','瞬間'],2,
    ['気温 means air temperature and is not a return date.','途中 means partway or on the way. It cannot name the final allowed return date.','期限 means a time limit. 来週の月曜日まで states the return deadline.','瞬間 is an instant, not the allowed time limit for returning a book.']),
  authored('qx-context-experience','vocabulary-context','vx-work-experience','この店で３年間働いたので、接客の（　）があります。',['契約','経験','給料','面接'],1,
    ['契約 is a contract. Three years of doing the job establishes experience, not the existence of a current contract.','経験 is experience. Having worked in the shop for three years gives customer-service experience.','給料 is salary. 接客の給料 is not the natural way to express three years of experience.','面接 is an interview. The completed years of work are not an interview.']),
  authored('qx-context-ingredients','vocabulary-context','vx-food-ingredient','夕食を作るために、肉や野菜などの（　）を買いました。',['季節','枝','症状','材料'],3,
    ['季節 is a season, which cannot be bought as part of dinner preparation.','枝 is a tree branch. It does not categorize the meat and vegetables used in cooking.','症状 means symptoms, not things used to make a meal.','材料 means ingredients or materials. Meat and vegetables are ingredients for dinner.']),
  authored('qx-context-charging','vocabulary-context','vx-technology-charging','携帯電話の電池がなくなりそうなので、出かける前に（　）します。',['充電','削除','撮影','投票'],0,
    ['充電 means charge the battery. It responds directly to the phone running out of power.','削除 means delete data, which does not refill the battery.','撮影 means take photos or film. It uses power rather than charging the phone.','投票 means vote and is unrelated to the phone’s battery.']),
  authored('qx-context-shade','vocabulary-context','vx-nature-shade','日差しが強いので、木の（　）で休みました。',['天井','日陰','熱','洪水'],1,
    ['天井 means an indoor ceiling. It is not the shaded space beneath a tree.','日陰 is shade. 木の日陰 is a natural place to escape strong sunlight.','熱 means heat or fever. Resting 木の熱で does not describe a sheltered place.','洪水 is a flood. It does not provide the shade sought here.']),
  authored('qx-context-cooperation','vocabulary-context','vx-community-cooperation','一人では運べないので、みんなで（　）して机を運びました。',['復習','洗濯','協力','就寝'],2,
    ['復習 means review study material. It does not mean working together to carry a desk.','洗濯 means washing clothes, not jointly carrying furniture.','協力 means cooperate. Working together solves the problem of the desk being too heavy for one person.','就寝 means go to bed. It cannot describe the joint work needed here.']),
  authored('qx-context-invitation','vocabulary-context','vx-culture-invitation','誕生日の食事会を開くので、友人を（　）しました。',['提出','通勤','宿泊','招待'],3,
    ['提出 means submit something. People are not submitted to a birthday meal.','通勤 means commute to work and does not invite a friend.','宿泊 means stay overnight. It does not express asking a friend to attend a meal.','招待 means invite someone as a guest. 友人を食事に招待する fits the occasion.']),
  authored('qx-context-calm','vocabulary-context','vx-feelings-calm-down','緊張したときは、深く息を吸って、気持ちを（　）ようにしています。',['落ち着かせる','引き出す','振り込む','蒸す'],0,
    ['落ち着かせる is the causative form of 落ち着く: calm something or someone. 気持ちを落ち着かせる means calm one’s feelings.','引き出す means withdraw or pull out. It does not mean calm one’s nerves.','振り込む means transfer money into an account. Feelings are not transferred this way.','蒸す means steam food, not calm feelings.']),
  authored('qx-context-service-counter','vocabulary-context','vx-services-service-counter','申請書の書き方が分からなかったので、役所の（　）で係の人に聞きました。',['海岸','窓口','居間','屋根'],1,
    ['海岸 is the seashore, not a municipal service point for application forms.','窓口 is a service counter. At the municipal office, staff can answer questions about the application there.','居間 is a living room in a home, not the office’s public service counter.','屋根 is a roof. It does not name the place where staff handle applications.']),

  authored('qx-paraphrase-errand','paraphrase','vx-daily-finish-errand','「銀行で用事を済ませました。」とほぼ同じ意味の文はどれですか。',['銀行での用事を終えました。','銀行の用事を忘れました。','銀行に行くのをやめました。','銀行で働き始めました。'],0,
    ['済ませる means get a task done. 用事を終える preserves that completed meaning.','Forgetting an errand does not mean completing it.','Deciding not to go is different from finishing the errand at the bank.','Starting employment at the bank is not the stated errand being completed.']),
  authored('qx-paraphrase-half-price','paraphrase','vx-shopping-half-price','「このパンは半額です。」とほぼ同じ意味の文はどれですか。',['このパンは無料です。','このパンはいつもの２倍の値段です。','このパンは元の値段の半分です。','このパンは半分だけ残っています。'],2,
    ['半額 means half the price, not zero payment.','Twice the price is the opposite of a half-price discount.','半額 means the item costs half its original price.','The sentence concerns price, not how much bread remains.']),
  authored('qx-paraphrase-stay','paraphrase','vx-travel-stay','「大阪に３日間滞在しました。」とほぼ同じ意味の文はどれですか。',['大阪まで３日かかりました。','大阪で３日間過ごしました。','３日前に大阪を出ました。','大阪に３回行きました。'],1,
    ['A three-day journey to Osaka differs from staying there for three days.','滞在する means remain in a place for a period. Spending three days in Osaka preserves the meaning.','Leaving Osaka three days ago states a departure date, not a three-day stay.','Three visits describe frequency, whereas ３日間 describes duration.']),
  authored('qx-paraphrase-next-day','paraphrase','vx-time-following-day','「注文した翌日に届きました。」とほぼ同じ意味の文はどれですか。',['注文する前の日に届きました。','注文してから１週間後に届きました。','注文したその日に届きました。','注文した次の日に届きました。'],3,
    ['翌日 is the following day, not the day before the order.','A week later is not the following day.','The same day would be 当日; 翌日 means the next day.','翌日 and 次の日 both refer to the day after the order.']),
  authored('qx-paraphrase-worry','paraphrase','vx-feelings-anxiety','「新しい仕事がうまくできるか不安です。」とほぼ同じ意味の文はどれですか。',['新しい仕事がうまくできるか心配です。','新しい仕事には全く興味がありません。','新しい仕事はもう全部終わりました。','新しい仕事が必ずうまくできると信じています。'],0,
    ['In this context, 不安 and 心配 both express worry about doing the new job well.','Anxiety about performing the job does not mean a lack of interest.','The original sentence expresses concern, not that the work is finished.','Certainty of success removes the uncertainty expressed by 不安.']),
  authored('qx-paraphrase-decline','paraphrase','vx-communication-decline','「友人からの誘いを断りました。」とほぼ同じ意味の文はどれですか。',['友人を自分から誘いました。','友人の誘いに喜んで応じました。','友人に、誘われても行けないと伝えました。','友人と会う場所を決めました。'],2,
    ['Inviting a friend yourself reverses who issued the invitation.','Accepting the invitation is the opposite of declining it.','断る means decline. Telling the friend you cannot attend preserves the refusal in this situation.','Choosing where to meet does not state that the invitation was declined.']),
  authored('qx-paraphrase-borrow','paraphrase','vx-services-borrow','「友人に辞書を借りました。」とほぼ同じ意味の文はどれですか。',['友人に辞書を売りました。','友人の辞書を一時的に使わせてもらいました。','友人に自分の辞書を貸しました。','友人の辞書を捨てました。'],1,
    ['Selling transfers ownership for payment; it is not borrowing.','Borrowing means temporarily using someone else’s item, with the expectation of returning it.','貸す would mean lend your own dictionary. 借りる means receive another person’s dictionary for temporary use.','Throwing away the dictionary does not mean borrowing it.']),
  authored('qx-paraphrase-record','paraphrase','vx-technology-record','「歩いた距離を記録しています。」とほぼ同じ意味の文はどれですか。',['歩いた距離を忘れようとしています。','歩く場所を友人に聞いています。','歩くのを毎日やめています。','歩いた距離を後で分かるように残しています。'],3,
    ['Recording preserves information rather than trying to forget it.','Asking where to walk concerns a route, not keeping information about distance walked.','The sentence does not say walking has stopped.','記録する means preserve information so it can be checked later.'],
  ),

  authored('qx-usage-budget','usage','vx-shopping-budget','「予算」の使い方として、最も自然な文はどれですか。',['旅行の予算を３万円に決めました。','急いで予算に乗って駅に行きました。','夕食の予算を塩で焼きました。','窓の予算が開いています。'],0,
    ['A budget is a planned amount of money. 決める and a yen amount fit 予算.','予算 is not a vehicle that can be boarded.','A budget cannot be cooked with salt; it is a spending plan.','A window is not a budget. 予算が開く does not describe a window being open.']),
  authored('qx-usage-pass','usage','vx-education-pass-exam','「合格」の使い方として、最も自然な文はどれですか。',['重い箱を合格に入れました。','明日の電車に合格を忘れました。','運転免許の試験に合格しました。','空が合格して雨になりました。'],2,
    ['合格 is passing a test, not a container for a box.','合格 is not a personal object that can be left on a train.','A test is marked with に: 試験に合格する means pass the test.','A sky does not pass a test. 合格する cannot describe it turning rainy.']),
  authored('qx-usage-consult','usage','vx-community-consultation','「相談」の使い方として、最も自然な文はどれですか。',['パンを相談して朝食を作りました。','困ったことを先生に相談しました。','駅から相談まで電車に乗りました。','相談が冷めたので温めました。'],1,
    ['Bread is not discussed as if 相談 were a cooking operation; the sentence does not express seeking advice.','相談する takes the person consulted with に and the matter with を. This sentence naturally describes asking the teacher for advice.','相談 is an act of consultation, not a destination station.','相談 is not food or a drink that becomes cold and can be warmed.']),
  authored('qx-usage-preserve','usage','vx-technology-save','「保存」の使い方として、最も自然な文はどれですか。',['保存で会社へ走りました。','山の保存から海が見えました。','先生に保存を質問しました。','書いた文書をパソコンに保存しました。'],3,
    ['保存 means saving or preserving, not a means of transportation.','保存 does not mean a mountain summit or viewpoint.','保存 itself does not mean a question. The natural expression would specify a question about saving, such as 保存方法について質問する.','文書を保存する naturally means save a document. パソコンに names where it is saved.']),
  authored('qx-usage-deposit-care','usage','vx-services-leave-in-care','「預ける」の使い方として、最も自然な文はどれですか。',['駅の受付に荷物を預けました。','机を歩いて預けました。','雨が強く預けました。','空を預けて晴れました。'],0,
    ['預ける takes an item with を and the person or place entrusted with it with に. This describes leaving luggage with reception.','Walking a desk does not form the item-and-recipient relation required by 預ける.','Rain becoming strong is not an act of entrusting an item to someone.','Entrusting the sky cannot describe the weather clearing.']),
  authored('qx-usage-reply','usage','vx-communication-reply-message','「返信」の使い方として、最も自然な文はどれですか。',['電車を返信して会社に行きました。','昼ご飯を返信して食べました。','友人のメールに返信しました。','返信の温度を高くしました。'],2,
    ['返信 means replying to a message, not using a train to travel.','A meal is eaten, not replied to as a written message.','メールに返信する naturally means reply to an email.','返信 is a written reply, not a temperature setting.']),
  authored('qx-usage-satisfaction','usage','vx-feelings-satisfaction','「満足」の使い方として、最も自然な文はどれですか。',['満足を切って野菜を焼きました。','ホテルのサービスに満足しました。','満足の切符でバスに乗りました。','机の下に満足が走りました。'],1,
    ['満足 is satisfaction, not an ingredient to cut.','The thing a person is satisfied with takes に. ホテルのサービスに満足する is natural.','満足 is not a type of ticket used for boarding a bus.','満足 is a feeling or state, not a creature that runs under a desk.']),
  authored('qx-usage-practice','usage','vx-education-revision','「復習」の使い方として、最も自然な文はどれですか。',['復習を財布に入れて払いました。','靴を復習して玄関に置きました。','復習の天気が晴れました。','授業の内容を家で復習しました。'],3,
    ['復習 is reviewing learned material, not money that can be paid.','Shoes are not lesson material to review in this sentence.','復習 does not name a weather condition.','復習する naturally takes learned content with を. The sentence describes reviewing the lesson at home.']),
];

export const expandedVocabularyQuestions: LexicalQuestion[] = [...readingQuestions, ...orthographyQuestions, ...authoredQuestions];
